version: "3.9"  # optional since v1.27.0
platform: linux/amd64
services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: 'products'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'myskel'
      MYSQL_ROOT_PASSWORD: 'myskel'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - '27017:27017'
    expose:
      - '27017'
    volumes:
      - mongo-db:/data/db
volumes:
  mongo-db:
  my-db: 